// ARTICLES
export const LOAD_ARTICLES = "LOAD_ARTICLES";
export const LOAD_ARTICLES_SUCCESS = "LOAD_ARTICLES_SUCCESS";
export const LOAD_ARTICLES_FAILURE = "LOAD_ARTICLES_FAILURE";

// ARTICLE SOURCES
export const LOAD_ARTICLE_SOURCES = "LOAD_ARTICLE_SOURCES";
export const LOAD_ARTICLE_SOURCES_SUCCESS = "LOAD_ARTICLE_SOURCES_SUCCESS";
export const LOAD_ARTICLE_SOURCES_FAILURE = "LOAD_ARTICLE_SOURCES_FAILURE";

// USER PREFERENCES
export const UPDATE_USER_PREFERENCES = "UPDATE_USER_PREFERENCES";
export const UPDATE_USER_PREFERENCES_SUCCESS = "UPDATE_USER_PREFERENCES_SUCCESS";
export const UPDATE_USER_PREFERENCES_FAILURE = "UPDATE_USER_PREFERENCES_FAILURE";

// USER REGISTRATION AND LOGIN
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
